drop table "BR_DOCTOR_PLAYER" cascade constraints PURGE;
drop table "BR_REFEREE_MATCH" cascade constraints PURGE;
drop table "COACH" cascade constraints PURGE;
drop table "DOCTOR" cascade constraints PURGE;
drop table "GROUPS" cascade constraints PURGE;
drop table "MATCH" cascade constraints PURGE;
drop table "PLAYER" cascade constraints PURGE;
drop table "PLAYER_CONTACT" cascade constraints PURGE;
drop table "REFEREE" cascade constraints PURGE;
drop table "STADIUM" cascade constraints PURGE;
drop table "TEAM" cascade constraints PURGE;
drop table "ZIPCODE" cascade constraints PURGE;
drop table "CARD" cascade constraints PURGE;
drop table "GOAL" cascade constraints PURGE;


CREATE TABLE ZIPCODE (
    PLAYER_ZIP VARCHAR2(10) PRIMARY KEY,
    PLAYER_CITY VARCHAR2(30),
    PLAYER_PROVINCE VARCHAR2(30)
);

CREATE TABLE COACH (
    COACH_ID NUMBER PRIMARY KEY,
    COACH_LAST_NAME VARCHAR2(30) NOT NULL,
    COACH_FIRST_NAME VARCHAR2(30) NOT NULL,
    NATIONALITY VARCHAR2(30)
);

CREATE TABLE REFEREE (
    REFEREE_ID NUMBER PRIMARY KEY,
    REFEREE_LAST_NAME VARCHAR(30) NOT NULL,
    REFEREE_FIRST_NAME VARCHAR(30) NOT NULL,
    NATIONALITY VARCHAR2(30)
);

CREATE TABLE GROUPS (
    GROUP_ID NUMBER PRIMARY KEY,
    GROUP_NAME VARCHAR2(20)
);

CREATE TABLE TEAM (
    TEAM_ID NUMBER PRIMARY KEY,
    TEAM_NAME VARCHAR2(30),
    COUNTRY VARCHAR2(30) NOT NULL,
    COACH_ID NUMBER,
    GROUP_ID NUMBER,
    CONSTRAINT fk_TEAM_COACH FOREIGN KEY (COACH_ID) REFERENCES COACH (COACH_ID),
    CONSTRAINT fk_TEAM_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID)
);

CREATE TABLE DOCTOR (
    DOCTOR_ID NUMBER PRIMARY KEY,
    DOCTOR_LAST_NAME VARCHAR2(30) NOT NULL,
    DOCTOR_FIRST_NAME VARCHAR2(30) NOT NULL,
    DOCTOR_TITLE VARCHAR(30) NOT NULL,
    TEAM_ID NUMBER,
    CONSTRAINT fk_DOCTOR_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID)
);

CREATE TABLE STADIUM (
    STADIUM_ID NUMBER PRIMARY KEY,
    CAPACITY NUMBER NOT NULL,
    STADIUM_ADDRESS VARCHAR2(60) NOT NULL,
    STADIUM_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE MATCH (
    MATCH_ID NUMBER PRIMARY KEY,
    MATCH_TIME VARCHAR2(10),
    MATCH_DATE DATE,
    TEAM_ID_HOME NUMBER,
    TEAM_ID_AWAY NUMBER,
    ROUND NUMBER,
    GROUP_ID NUMBER,
    STADIUM_ID NUMBER,
    CONSTRAINT fk_MATCH_TEAM_HOME FOREIGN KEY (TEAM_ID_HOME) REFERENCES TEAM (TEAM_ID),
    CONSTRAINT fk_MATCH_TEAM_AWAY FOREIGN KEY (TEAM_ID_AWAY) REFERENCES TEAM (TEAM_ID),
    CONSTRAINT fk_MATCH_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID),
    CONSTRAINT fk_MATCH_STADIUM FOREIGN KEY (STADIUM_ID) REFERENCES STADIUM (STADIUM_ID)
);


CREATE TABLE BR_REFEREE_MATCH (
    REFEREE_ID NUMBER,
    MATCH_ID NUMBER,
    CONSTRAINT pk_REFEREE_MATCH PRIMARY KEY (REFEREE_ID, MATCH_ID),
    CONSTRAINT fk_REFEREE_MATCH1 FOREIGN KEY (REFEREE_ID) REFERENCES REFEREE (REFEREE_ID),
    CONSTRAINT fk_REFEREE_MATCH2 FOREIGN KEY (MATCH_ID) REFERENCES MATCH (MATCH_ID)
);

CREATE TABLE PLAYER (
    PLAYER_ID NUMBER PRIMARY KEY,
    PLAYER_LAST_NAME VARCHAR2(30) NOT NULL,
    PLAYER_FIRST_NAME VARCHAR2(30) NOT NULL,
    DOB DATE,
    PLAYER_NO NUMBER NOT NULL,
    NATIONALITY VARCHAR2(30),
    POSITION VARCHAR2(30),
    PLAYER_STREET VARCHAR2(50) NOT NULL,
    PLAYER_ZIP VARCHAR2(10),
    TEAM_ID NUMBER,
    CONSTRAINT fk_PLAYER_ZIP FOREIGN KEY (PLAYER_ZIP) REFERENCES ZIPCODE (PLAYER_ZIP),
    CONSTRAINT fk_PLAYER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID)
);

CREATE TABLE CARD (
    CARD_ID NUMBER PRIMARY KEY,
    CARD_COLOUR VARCHAR2(20) NOT NULL,
    CARD_TIME VARCHAR(10),
    PLAYER_ID NUMBER,
    MATCH_ID NUMBER,
    REFEREE_ID NUMBER,
    CONSTRAINT fk_CARD_PLAYER FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID),
    CONSTRAINT fk_CARD_MATCH1 FOREIGN KEY (MATCH_ID) REFERENCES MATCH (MATCH_ID),
    CONSTRAINT fk_CARD_MATCH2 FOREIGN KEY (REFEREE_ID) REFERENCES REFEREE (REFEREE_ID)
);

CREATE TABLE PLAYER_CONTACT (
    CONTACT_ID NUMBER PRIMARY KEY,
    PLAYER_PHONE_NUMBER NUMBER NOT NULL,
    PLAYER_ID NUMBER,
    CONSTRAINT fk_CONTACT_PHONE FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID)
);

CREATE TABLE BR_DOCTOR_PLAYER (
    DOCTOR_ID NUMBER,
    PLAYER_ID NUMBER,
    CONSTRAINT pk_DOCTOR_PLAYER PRIMARY KEY (DOCTOR_ID, PLAYER_ID),
    CONSTRAINT fk_DOCTOR_PLAYER1 FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (DOCTOR_ID),
    CONSTRAINT fk_DOCTOR_PLAYER2 FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID)
);

CREATE TABLE GOAL (
    GOAL_ID NUMBER PRIMARY KEY,
    SCORE_TIME VARCHAR2(10) NOT NULL,
    PLAYER_ID NUMBER,
    MATCH_ID NUMBER,
    CONSTRAINT fk_GOAL_PLAYER FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (PLAYER_ID),
    CONSTRAINT fk_GOAL_MATCH FOREIGN KEY (MATCH_ID) REFERENCES MATCH (MATCH_ID)
);

INSERT ALL
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('M4Y 2SE', 'Toronto', 'Ontario')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('M4Y 1W1', 'Toronto', 'Ontario')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('L4E 4G1', 'Richmond Hill', 'Ontario')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('V5K 4S1', 'Vancouver', 'Ontario')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('V6V 0A1', 'Toronto', 'Ontario')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('08001', 'Barcelona', 'Catalonia')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('46001', 'Valencia', 'Valencia')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('1201', 'Geneva', 'Geneva')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('90210', 'Beverly Hills', 'California')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('00118', 'Roma', 'Roma')
  INTO ZIPCODE (PLAYER_ZIP, PLAYER_CITY, PLAYER_PROVINCE) VALUES ('20121', 'Milan', 'Milano')
SELECT * FROM DUAL;

INSERT ALL
    INTO COACH (COACH_ID, COACH_LAST_NAME, COACH_FIRST_NAME, NATIONALITY) VALUES (1, 'Nurse', 'Nick', 'American')
    INTO COACH (COACH_ID, COACH_LAST_NAME, COACH_FIRST_NAME, NATIONALITY) VALUES (2, 'Nash', 'Steve', 'Canadian')
    INTO COACH (COACH_ID, COACH_LAST_NAME, COACH_FIRST_NAME, NATIONALITY) VALUES (3, 'D’Antoni', 'Mike', 'Italian')
    INTO COACH (COACH_ID, COACH_LAST_NAME, COACH_FIRST_NAME, NATIONALITY) VALUES (4, 'Scariolo', 'Sergio', 'Spanish')
SELECT * FROM DUAL;

INSERT ALL
    INTO REFEREE (REFEREE_ID, REFEREE_LAST_NAME, REFEREE_FIRST_NAME, NATIONALITY) VALUES (1, 'Brothers', 'Tony', 'American')
    INTO REFEREE (REFEREE_ID, REFEREE_LAST_NAME, REFEREE_FIRST_NAME, NATIONALITY) VALUES (2, 'Malloy', 'Ed', 'American')
    INTO REFEREE (REFEREE_ID, REFEREE_LAST_NAME, REFEREE_FIRST_NAME, NATIONALITY) VALUES (3, 'Kallio', 'Matt', 'Canadian')
    INTO REFEREE (REFEREE_ID, REFEREE_LAST_NAME, REFEREE_FIRST_NAME, NATIONALITY) VALUES (4, 'Lahez', 'Antonio', 'Spanish')
SELECT * FROM DUAL;

INSERT ALL
    INTO GROUPS (GROUP_ID, GROUP_NAME) VALUES (1, 'Group A')
    INTO GROUPS (GROUP_ID, GROUP_NAME) VALUES (2, 'Group B')
    INTO GROUPS (GROUP_ID, GROUP_NAME) VALUES (3, 'Group C')
SELECT * FROM DUAL;

INSERT ALL
    INTO TEAM (TEAM_ID, TEAM_NAME, COUNTRY, COACH_ID, GROUP_ID) VALUES (1, 'Canada', 'Canada', 2, 1)
    INTO TEAM (TEAM_ID, TEAM_NAME, COUNTRY, COACH_ID, GROUP_ID) VALUES (2, 'America', 'America', 1, 1)
    INTO TEAM (TEAM_ID, TEAM_NAME, COUNTRY, COACH_ID, GROUP_ID) VALUES (3, 'Italy', 'Italy', 3, 2)
    INTO TEAM (TEAM_ID, TEAM_NAME, COUNTRY, COACH_ID, GROUP_ID) VALUES (4, 'Spain', 'Spain', 4, 2)
SELECT * FROM DUAL;

INSERT ALL
    INTO DOCTOR (DOCTOR_ID, DOCTOR_LAST_NAME, DOCTOR_FIRST_NAME, DOCTOR_TITLE, TEAM_ID) VALUES (1, 'Williams', 'Riley', 'MD', 2)
    INTO DOCTOR (DOCTOR_ID, DOCTOR_LAST_NAME, DOCTOR_FIRST_NAME, DOCTOR_TITLE, TEAM_ID) VALUES (2, 'Lisa', 'Callahan', 'MD', 2)
    INTO DOCTOR (DOCTOR_ID, DOCTOR_LAST_NAME, DOCTOR_FIRST_NAME, DOCTOR_TITLE, TEAM_ID) VALUES (3, 'Naismith', 'James', 'MD', 1)
    INTO DOCTOR (DOCTOR_ID, DOCTOR_LAST_NAME, DOCTOR_FIRST_NAME, DOCTOR_TITLE, TEAM_ID) VALUES (4, 'Bargnani', 'Andrea', 'MD', 3)
    INTO DOCTOR (DOCTOR_ID, DOCTOR_LAST_NAME, DOCTOR_FIRST_NAME, DOCTOR_TITLE, TEAM_ID) VALUES (5, 'Calderon', 'Jose', 'MD', 4)
    INTO DOCTOR (DOCTOR_ID, DOCTOR_LAST_NAME, DOCTOR_FIRST_NAME, DOCTOR_TITLE, TEAM_ID) VALUES (6, 'Gasol', 'Pau', 'MD', 4)
SELECT * FROM DUAL;

INSERT ALL
    INTO STADIUM (STADIUM_ID, CAPACITY, STADIUM_ADDRESS, STADIUM_NAME) VALUES (1, 50000, '40 Bay Street', 'Air Canada Center')
    INTO STADIUM (STADIUM_ID, CAPACITY, STADIUM_ADDRESS, STADIUM_NAME) VALUES (2, 45000, '55 Yonge Street', 'Scotiabank Arena')
SELECT * FROM DUAL;

INSERT ALL
    INTO MATCH (MATCH_ID, MATCH_TIME, MATCH_DATE, TEAM_ID_HOME, TEAM_ID_AWAY, ROUND, GROUP_ID, STADIUM_ID) VALUES (1, '11:30AM', TO_DATE('2022-05-03', 'YYYY-MM-DD'), 1, 2, 1, 1, 1)
    INTO MATCH (MATCH_ID, MATCH_TIME, MATCH_DATE, TEAM_ID_HOME, TEAM_ID_AWAY, ROUND, GROUP_ID, STADIUM_ID) VALUES (2, '10:30AM', TO_DATE('2022-05-02', 'YYYY-MM-DD'), 3, 4, 1, 2, 2)
SELECT * FROM DUAL;

INSERT ALL
    INTO BR_REFEREE_MATCH (REFEREE_ID, MATCH_ID) VALUES (1, 1)
    INTO BR_REFEREE_MATCH (REFEREE_ID, MATCH_ID) VALUES (2, 1)
    INTO BR_REFEREE_MATCH (REFEREE_ID, MATCH_ID) VALUES (3, 2)
    INTO BR_REFEREE_MATCH (REFEREE_ID, MATCH_ID) VALUES (4, 2)
SELECT * FROM DUAL;

INSERT ALL
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (1, 'Wade', 'Dwyane', '1982-01-17', 3, 'American', 'SG', '1 Filler St', '90210', 2)
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (2, 'James', 'LeBron', '1984-12-30', 23, 'American', 'SF', '2 Filler St', '90210', 2)
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (3, 'Murray', 'Jamal', '1997-02-23', 27, 'Canadian', 'PG', '3 Filler St', 'M4Y 2SE', 1)
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (4, 'Barrett', 'RJ', '2000-06-14', 9, 'Canadian', 'SG', '4 Filler St', 'M4Y 1W1', 1)
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (5, 'Wiggins', 'Andrew', '1995-02-23', 22, 'Canadian', 'SF', '5 Filler St', 'V5K 4S1', 1)
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (6, 'Joseph', 'Cory', '1991-08-20', 6, 'Canadian', 'PG', '6 Filler St', 'V5K 4S1', 1)
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (7, 'Rubio', 'Ricky', '1990-10-21', 11, 'Spanish', 'PG', '7 Filler St', '46001', 4)
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (8, 'Garbajosa', 'Jorge', '1977-12-19', 15, 'Spanish', 'PF', '8 Filler St', '08001', 4)
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (9, 'Gallinari', 'Danilo', '1988-08-08', 8, 'Italian', 'SF', '9 Filler St', '00118', 3)
    INTO PLAYER (PLAYER_ID, PLAYER_LAST_NAME, PLAYER_FIRST_NAME, DOB, PLAYER_NO, NATIONALITY, POSITION, PLAYER_STREET, PLAYER_ZIP, TEAM_ID) VALUES (10, 'Belinelli', 'Marco', '1986-03-25', 18, 'Italian', 'SG', '10 Filler St', '20121', 3)
SELECT * FROM DUAL;

INSERT ALL
    INTO CARD (CARD_ID, CARD_COLOUR, CARD_TIME, PLAYER_ID, MATCH_ID, REFEREE_ID) VALUES (1, 'Yellow', '12:43', 1, 1, 2)
    INTO CARD (CARD_ID, CARD_COLOUR, CARD_TIME, PLAYER_ID, MATCH_ID, REFEREE_ID) VALUES (2, 'Yellow', '33:27', 3, 1, 3)
    INTO CARD (CARD_ID, CARD_COLOUR, CARD_TIME, PLAYER_ID, MATCH_ID, REFEREE_ID) VALUES (3, 'Red', '44:12', 6, 1, 3)
    INTO CARD (CARD_ID, CARD_COLOUR, CARD_TIME, PLAYER_ID, MATCH_ID, REFEREE_ID) VALUES (4, 'Red', '59:01', 9, 2, 4)
    INTO CARD (CARD_ID, CARD_COLOUR, CARD_TIME, PLAYER_ID, MATCH_ID, REFEREE_ID) VALUES (5, 'Yellow', '24:55', 8, 2, 1)
SELECT * FROM DUAL;

INSERT ALL
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (1, 1234567890, 1)
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (2, 2224232323, 1)
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (3, 4343423233, 2)
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (4, 2222222222, 3)
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (5, 6555549444, 4)
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (6, 3455555555, 4)
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (7, 0490999999, 5)
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (8, 1112222221, 5)
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (9, 2333333333, 6)
    INTO PLAYER_CONTACT (CONTACT_ID, PLAYER_PHONE_NUMBER, PLAYER_ID) VALUES (10, 3232323233, 7)
SELECT * FROM DUAL;

INSERT ALL
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (1, 2)
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (1, 4)
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (1, 5)
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (2, 1)
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (2, 3)
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (2, 2)
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (3, 7)
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (3, 8)
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (4, 3)
    INTO BR_DOCTOR_PLAYER (DOCTOR_ID, PLAYER_ID) VALUES (4, 9)
SELECT * FROM DUAL;

INSERT ALL
    INTO GOAL (GOAL_ID, SCORE_TIME, PLAYER_ID, MATCH_ID) VALUES (1, '43:22', 1, 1)
    INTO GOAL (GOAL_ID, SCORE_TIME, PLAYER_ID, MATCH_ID) VALUES (2, '20:36', 3, 1)
    INTO GOAL (GOAL_ID, SCORE_TIME, PLAYER_ID, MATCH_ID) VALUES (3, '86:22', 1, 1)
    INTO GOAL (GOAL_ID, SCORE_TIME, PLAYER_ID, MATCH_ID) VALUES (4, '11:22', 8, 2)
    INTO GOAL (GOAL_ID, SCORE_TIME, PLAYER_ID, MATCH_ID) VALUES (5, '36:59', 6, 2)
    INTO GOAL (GOAL_ID, SCORE_TIME, PLAYER_ID, MATCH_ID) VALUES (6, '66:59', 6, 2)
SELECT * FROM DUAL;